#                                      #
#        Instalação do Postgre         #
#                                      #
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: postgre
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
          - name: postgre
            image: postgres:13.1
            env:
              - name: POSTGRES_PASSWORD
                value: Passw0rdPTG
              - name: POSTGRES_USER
                value: reviewfilmes
              - name: POSTGRES_DB
                value: reviewfilmes
            ports:
              - containerPort: 5432
---
#                                      #
#   Instalação do service do Postgre   #
#                                      #
apiVersion: v1
kind: Service
metadata: 
   name: postgre
spec: 
   selector:
      app: postgre
   ports:
     - port: 5432
---
#                                           #
# Instalação da Aplicação Web e serviço     #
#                                           #
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: reviewfilmes
spec: 
  replicas: 10
  selector:
    matchLabels:
      app: reviewfilmes
  template:
    metadata:
      labels:
        app: reviewfilmes
    spec:
      containers:
          - name: reviewfilmes
            image: lanvsc/review-filmes:v1
            env:
              - name: ASPNETCORE_HTTP_PORTS
                value: "8080"
              - name: ConnectionStrings__DefaultConnection
                value: "HOST=postgre;Database=reviewfilmes;Username=reviewfilmes;Password=Passw0rdPTG"
            ports:
              - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: reviewfilmes
spec:
  selector:
    app: reviewfilmes
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000 
  type: NodePort