name: CI-CD
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs: 
  CI: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4.1.7

      - name: Login no Docker Hub
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  

      - name: Construção da Imagem Docker e Envio para o Docker Hub
        uses: docker/build-push-action@v6.3.0
        with:
          context: ./src
          push: true
          file: ./src/Review-Filmes.Web/Dockerfile
          tags: |
            xenxem/review-filmes:v${{ github.run_number }}
            xenxem/review-filmes:latest
  CD:   
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
      - name: Checkout do código fonte
        uses: actions/checkout@v4.1.7

      - name: Configuração do AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         aws-region: us-east-1

      - name: Configuração do Kubeconfig
        run: aws eks update-kubeconfig --name eksAula

      - name: Deploy no Kubernetes
        uses: Azure/k8s-deploy@v5.0.0
        with:          
          manifests: |
            ./k8s/deployment.yml
          images: |
            xenxem/review-filmes:v${{ github.run_number }}          
      
      - name: Passo 01
        run: echo "Deploy da aplicação"

